baseURL = "https://ayamir.github.io"
languageCode = "en-US"
title = "j4breu (Joel Abreu)"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Joel Abreu"
  description = "Code is measured by the time it takes to understand and use it, not by the number of lines."
  github = "j4breu"
  facebook = "j4breu"
  twitter = "j4breu"
  linkedin = "j4breu"
  email = "joelabreurojas@gmail.com"
  keywords = "Database Design, Memory Management, Open-Source Development, Web Scraping"
  rss = true
  userStatusEmoji = "👀"
  favicon = "/images/favicon.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Puerto Ordaz, Venezuela"
